# -*- coding: utf-8 -*-
"""Cópia de 15-bonus-data-cleaning-metal-bands.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uhf3Qbb_PrEvfg86ZBx6ohETHanZzBr4
"""

import pandas as pd

# death_metal.csv
url = 'https://drive.google.com/file/d/11HsCgxJL_PtJ8xxdT5VZbw6e0y0-VKag/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
bands = pd.read_csv(path)

bands.head()

bands.info()

"""### **Exercise 1:**
Cleaning the 'name' column

The names of the bands are messy. They have some extra characters like '\*\*' at the begining and '?>' at the end. Remove them using any or all of these methods:  
- [pandas.Series.str.replace](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html)
- [pandas.Series.str.lstrip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.lstrip.html)
- [pandas.Series.str.rstrip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.rstrip.html)
- [pandas.Series.str.strip](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.strip.html)
"""

bands['name'].head(5)

bands['name'] = bands['name'].str.replace(r'[^\w\s]', '', regex=True)
bands

"""### **Exercise 2:**
Cleaning the country column

The country column has all countries written with small capital letter. Change them so they have all capital letters.  
Best method for this is: [pandas.Series.str.title](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.title.html)
"""

bands['country'].head(5)

bands['country'] = bands['country'].str.title()
bands

"""### **Exercise 3:**
Cleaning the status column

The status column has some abbreviations instead of the real status.  
Change them in accordance with this:  
* ac = Active  
* su = Split-up  
* cn = Changed name  
* oh = On hold  
* un = Unknown

You can use  
pandas.Series.str.replace -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html  
or you can create a dictionary and remap values according to it with  
pandas.Series.replace -> https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html
"""

bands['status'].head(5)

bands.status = bands.status.map({
  'ac': 'Active',
  'su': 'Split-up',
  'cn': 'Changed name',
  'oh': 'On hold',
  'un': 'Unknown'
})
bands

"""### **Exercise 4:**
Cleaning the genre column

The column genre has genres in a single string separated by character /  
1. First, transform the string to list of strings  
(e.g. 'Avant-garde Black/Death Metal'    to     \[Avant-garde Black, Death Metal\]  
1. Then, create a new column 'number_of_genres' where you will store the number of genres in each list.  

Methods you can use are:  
pandas.Series.str.split -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.split.html  
pandas.Series.str.len -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.len.html
"""

bands['genre'].head(5)

bands.genre = bands.genre.str.split('/')
bands.insert(bands.columns.get_loc('genre') + 1, 'number_of_genres', bands.genre.str.len())
bands

"""### **Exercise 5:**
Cleaning the active column

The column `active` contains information about the years when a band was active or '?' if the status or year is unknown.  

Create two new columns
- `active_from`: when the band formed
- `active_to`: when the band broke up

and fill them with the information contained in the column `active`.  

Method you can use is: pandas.Series.str.extract -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.extract.html#
"""

bands['active'].head(5)

bands = pd.concat([bands, bands['active'].str.extract(r'(?P<active_from>.*)-(?P<active_to>.*)')], axis=1)
bands

"""### **Exercise 6**
Counting the themes

Count how many times do the words Love, Life, Death repeat in a themes column.  
Method you can use is:  
pandas.Series.str.count -> https://pandas.pydata.org/docs/reference/api/pandas.Series.str.count.html  
"""

bands['theme'].head(5)

{ theme: bands['theme'].str.count(theme).sum() for theme in [ 'Love', 'Life', 'Death' ] }

"""## Final result"""

bands