# -*- coding: utf-8 -*-
"""Cópia de 8-bonus-challenge__sql-to-pd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIfPZvMhoChp4NQGZvFOYHYeRWIxaN6e

# From SQL to pandas challenge 8
"""

# import libraries
import pandas as pd

# load data
# This code is made to load our data stored on Google Drive
def gd_path(file_id):
    """Generate a shareable link from Google Drive file id."""
    return f"https://drive.google.com/uc?export=download&id={file_id}"

# Google Drive file ids
files_id = {
    "sales": "1fzFc9rwYmVIPaGOFmhLVxCi3kg19vNU2",
    "authors": "1fEF89Nhe61EebAljKlwFwfEuokK0o6aJ"
}

# Read data from Google Drive
sales = pd.read_csv(gd_path(files_id["sales"]), sep=";")
authors = pd.read_csv(gd_path(files_id["authors"]), sep=";")

"""## 1.&nbsp;Select the top 5 sales with most quantity sold between 1993-03-11 and 1994-09-13 from the table sales"""

sales.ord_date = pd.to_datetime(sales.ord_date)
sales[sales.ord_date.between('1993-03-11', '1994-09-13')].sort_values('qty', ascending=False).head(5)

"""### Hint:

In SQL the syntax is:

```sql
SELECT *
FROM sales
WHERE ord_date BETWEEN '1993-03-11' AND '1994-09-13'
ORDER BY qty DESC
LIMIT 5;
```

## 2.&nbsp;How many authors have an "i" in their first name, and are from Utah, Maryland, or Kansas?
"""

(authors.au_fname.str.contains('i', case=False) & authors.state.isin(['UT','MD','KS'])).sum()

"""### Hint:

In SQL the syntax is:

```sql
SELECT COUNT(*)
FROM authors
WHERE au_fname LIKE '%i%'
AND state IN ('CA' , 'MD', 'KS');
```

## 3.&nbsp;In California, how many authors are there in cities that contain an "o" in the name?
   - Show only results for cities with more than 1 author.
   - Sort the cities ascendingly by author count.
"""

((authors.state == 'CA') & authors.city.str.contains('o', case=False)).sum()

(
    authors[
        (authors.state == 'CA')
      & authors.city.str.contains('o', case=False)
    ]
    .groupby('city')
    .au_id.count()
    [lambda result: result > 1]
    .sort_values()
)

"""### Hint:

In SQL the syntax is:

```sql
SELECT city, COUNT(au_fname)
FROM authors
WHERE state = 'CA'
AND city LIKE '%o%'
GROUP BY city
HAVING COUNT(au_fname) > 1
ORDER BY COUNT(au_fname);
```
"""